### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by MHA5** [kimlalman28/CPU_Scheduling_Simulator#1]
when running any of the scheduling algorithms, following exception occurs
run:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at Assignment2.main(Assignment2.java:36)
C:\Users\Naram Dil\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 0 seconds)

**Comment by kimlalman28** [comment]
@brainwashed55 how are you running the code in the command line? It should be like `java Assignment2 FCFS`.

**Comment by MHA5** [comment]
.
